declare module 'lucide-react' {
  import { ComponentType, SVGProps } from 'react'
  
  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: number | string
    absoluteStrokeWidth?: boolean
  }
  
  export const Activity: ComponentType<IconProps>
  export const AlertCircle: ComponentType<IconProps>
  export const AlertTriangle: ComponentType<IconProps>
  export const ArrowDown: ComponentType<IconProps>
  export const ArrowLeft: ComponentType<IconProps>
  export const ArrowRight: ComponentType<IconProps>
  export const ArrowUp: ComponentType<IconProps>
  export const Bell: ComponentType<IconProps>
  export const Calendar: ComponentType<IconProps>
  export const Camera: ComponentType<IconProps>
  export const Car: ComponentType<IconProps>
  export const Check: ComponentType<IconProps>
  export const CheckCircle: ComponentType<IconProps>
  export const ChevronDown: ComponentType<IconProps>
  export const ChevronLeft: ComponentType<IconProps>
  export const ChevronRight: ComponentType<IconProps>
  export const ChevronUp: ComponentType<IconProps>
  export const Clock: ComponentType<IconProps>
  export const Copy: ComponentType<IconProps>
  export const Crown: ComponentType<IconProps>
  export const Download: ComponentType<IconProps>
  export const Edit: ComponentType<IconProps>
  export const Eye: ComponentType<IconProps>
  export const FileCheck: ComponentType<IconProps>
  export const FileText: ComponentType<IconProps>
  export const Filter: ComponentType<IconProps>
  export const Heart: ComponentType<IconProps>
  export const Home: ComponentType<IconProps>
  export const Image: ComponentType<IconProps>
  export const Info: ComponentType<IconProps>
  export const Loader2: ComponentType<IconProps>
  export const Lock: ComponentType<IconProps>
  export const LogOut: ComponentType<IconProps>
  export const Mail: ComponentType<IconProps>
  export const Menu: ComponentType<IconProps>
  export const MoreHorizontal: ComponentType<IconProps>
  export const MoreVertical: ComponentType<IconProps>
  export const PenSquare: ComponentType<IconProps>
  export const Plus: ComponentType<IconProps>
  export const Printer: ComponentType<IconProps>
  export const RefreshCw: ComponentType<IconProps>
  export const Scan: ComponentType<IconProps>
  export const Search: ComponentType<IconProps>
  export const Settings: ComponentType<IconProps>
  export const Star: ComponentType<IconProps>
  export const Tag: ComponentType<IconProps>
  export const Trash2: ComponentType<IconProps>
  export const TrendingUp: ComponentType<IconProps>
  export const Trophy: ComponentType<IconProps>
  export const Upload: ComponentType<IconProps>
  export const User: ComponentType<IconProps>
  export const Users: ComponentType<IconProps>
  export const X: ComponentType<IconProps>
  export const ZoomIn: ComponentType<IconProps>
  export const Briefcase: ComponentType<IconProps>
  export const BadgeCheck: ComponentType<IconProps>
  export const ZoomIn: ComponentType<IconProps>
  export const Briefcase: ComponentType<IconProps>
  export const PenSquare: ComponentType<IconProps>
  export const Users: ComponentType<IconProps>
  export const Star: ComponentType<IconProps>
  export const Tag: ComponentType<IconProps>
  export const BadgeCheck: ComponentType<IconProps>
  export const Crown: ComponentType<IconProps>
  export const Settings: ComponentType<IconProps>
  export const Heart: ComponentType<IconProps>
  export const Bell: ComponentType<IconProps>
  export const Menu: ComponentType<IconProps>
  export const Trash2: ComponentType<IconProps>
  export const Scan: ComponentType<IconProps>
  export const BookOpen: ComponentType<IconProps>
  export const Code: ComponentType<IconProps>
  export const Package: ComponentType<IconProps>
  export const Shield: ComponentType<IconProps>
  export const Zap: ComponentType<IconProps>
  export const Globe: ComponentType<IconProps>
  export const Database: ComponentType<IconProps>
  export const Server: ComponentType<IconProps>
  export const Smartphone: ComponentType<IconProps>
  export const Monitor: ComponentType<IconProps>
  export const Palette: ComponentType<IconProps>
  export const Layers: ComponentType<IconProps>
  export const GitBranch: ComponentType<IconProps>
  export const GitCommit: ComponentType<IconProps>
  export const GitPullRequest: ComponentType<IconProps>
  export const Github: ComponentType<IconProps>
  export const ExternalLink: ComponentType<IconProps>
  export const File: ComponentType<IconProps>
  export const Folder: ComponentType<IconProps>
  export const FolderOpen: ComponentType<IconProps>
  export const Hash: ComponentType<IconProps>
  export const HelpCircle: ComponentType<IconProps>
  export const Info: ComponentType<IconProps>
  export const Link: ComponentType<IconProps>
  export const List: ComponentType<IconProps>
  export const MapPin: ComponentType<IconProps>
  export const MessageSquare: ComponentType<IconProps>
  export const Minus: ComponentType<IconProps>
  export const Moon: ComponentType<IconProps>
  export const Move: ComponentType<IconProps>
  export const Music: ComponentType<IconProps>
  export const Paperclip: ComponentType<IconProps>
  export const Phone: ComponentType<IconProps>
  export const Play: ComponentType<IconProps>
  export const PlayCircle: ComponentType<IconProps>
  export const Power: ComponentType<IconProps>
  export const Radio: ComponentType<IconProps>
  export const Save: ComponentType<IconProps>
  export const Send: ComponentType<IconProps>
  export const Share: ComponentType<IconProps>
  export const Share2: ComponentType<IconProps>
  export const Shield: ComponentType<IconProps>
  export const SkipBack: ComponentType<IconProps>
  export const SkipForward: ComponentType<IconProps>
  export const Slash: ComponentType<IconProps>
  export const Sliders: ComponentType<IconProps>
  export const Square: ComponentType<IconProps>
  export const StopCircle: ComponentType<IconProps>
  export const Sun: ComponentType<IconProps>
  export const Target: ComponentType<IconProps>
  export const Terminal: ComponentType<IconProps>
  export const ThumbsDown: ComponentType<IconProps>
  export const ThumbsUp: ComponentType<IconProps>
  export const ToggleLeft: ComponentType<IconProps>
  export const ToggleRight: ComponentType<IconProps>
  export const Tool: ComponentType<IconProps>
  export const Type: ComponentType<IconProps>
  export const Umbrella: ComponentType<IconProps>
  export const Volume: ComponentType<IconProps>
  export const Volume1: ComponentType<IconProps>
  export const Volume2: ComponentType<IconProps>
  export const VolumeX: ComponentType<IconProps>
  export const Wifi: ComponentType<IconProps>
  export const WifiOff: ComponentType<IconProps>
  export const Wind: ComponentType<IconProps>
  export const Wrench: ComponentType<IconProps>
  export const Youtube: ComponentType<IconProps>
  export const Key: ComponentType<IconProps>
  export const BarChart3: ComponentType<IconProps>
  export const PieChart: ComponentType<IconProps>
  export const TrendingDown: ComponentType<IconProps>
  export const DollarSign: ComponentType<IconProps>
  export const Euro: ComponentType<IconProps>
  export const CreditCard: ComponentType<IconProps>
  export const Receipt: ComponentType<IconProps>
  export const ShoppingCart: ComponentType<IconProps>
  export const Store: ComponentType<IconProps>
  export const Truck: ComponentType<IconProps>
  export const Building: ComponentType<IconProps>
  export const Home: ComponentType<IconProps>
  export const Map: ComponentType<IconProps>
  export const Navigation: ComponentType<IconProps>
  export const Compass: ComponentType<IconProps>
  export const Flag: ComponentType<IconProps>
  export const Award: ComponentType<IconProps>
  export const Medal: ComponentType<IconProps>
  export const Trophy: ComponentType<IconProps>
  export const Gift: ComponentType<IconProps>
  export const PartyPopper: ComponentType<IconProps>
  export const Sparkles: ComponentType<IconProps>
  export const Star: ComponentType<IconProps>
  export const Heart: ComponentType<IconProps>
  export const Smile: ComponentType<IconProps>
  export const Frown: ComponentType<IconProps>
  export const Meh: ComponentType<IconProps>
  export const Laugh: ComponentType<IconProps>
  export const Angry: ComponentType<IconProps>
  export const Surprise: ComponentType<IconProps>
  export const Wink: ComponentType<IconProps>
  export const Tongue: ComponentType<IconProps>
  export const ThumbsUp: ComponentType<IconProps>
  export const ThumbsDown: ComponentType<IconProps>
  export const Clap: ComponentType<IconProps>
  export const Wave: ComponentType<IconProps>
  export const Point: ComponentType<IconProps>
  export const Hand: ComponentType<IconProps>
  export const Handshake: ComponentType<IconProps>
  export const Fingerprint: ComponentType<IconProps>
  export const Eye: ComponentType<IconProps>
  export const EyeOff: ComponentType<IconProps>
  export const Ear: ComponentType<IconProps>
  export const Nose: ComponentType<IconProps>
  export const Mouth: ComponentType<IconProps>
  export const Brain: ComponentType<IconProps>
  export const Heart: ComponentType<IconProps>
  export const Lungs: ComponentType<IconProps>
  export const Stomach: ComponentType<IconProps>
  export const Bone: ComponentType<IconProps>
  export const DNA: ComponentType<IconProps>
  export const Microscope: ComponentType<IconProps>
  export const TestTube: ComponentType<IconProps>
  export const Flask: ComponentType<IconProps>
  export const Beaker: ComponentType<IconProps>
  export const Atom: ComponentType<IconProps>
  export const Molecule: ComponentType<IconProps>
  export const Pill: ComponentType<IconProps>
  export const Syringe: ComponentType<IconProps>
  export const Thermometer: ComponentType<IconProps>
  export const Stethoscope: ComponentType<IconProps>
  export const Bandage: ComponentType<IconProps>
  export const FirstAid: ComponentType<IconProps>
  export const Ambulance: ComponentType<IconProps>
  export const Hospital: ComponentType<IconProps>
  export const Cross: ComponentType<IconProps>
  export const Plus: ComponentType<IconProps>
  export const Minus: ComponentType<IconProps>
  export const Divide: ComponentType<IconProps>
  export const Percent: ComponentType<IconProps>
  export const Infinity: ComponentType<IconProps>
  export const Pi: ComponentType<IconProps>
  export const Sigma: ComponentType<IconProps>
  export const Omega: ComponentType<IconProps>
  export const Alpha: ComponentType<IconProps>
  export const Beta: ComponentType<IconProps>
  export const Gamma: ComponentType<IconProps>
  export const Delta: ComponentType<IconProps>
  export const Epsilon: ComponentType<IconProps>
  export const Zeta: ComponentType<IconProps>
  export const Eta: ComponentType<IconProps>
  export const Theta: ComponentType<IconProps>
  export const Iota: ComponentType<IconProps>
  export const Kappa: ComponentType<IconProps>
  export const Lambda: ComponentType<IconProps>
  export const Mu: ComponentType<IconProps>
  export const Nu: ComponentType<IconProps>
  export const Xi: ComponentType<IconProps>
  export const Omicron: ComponentType<IconProps>
  export const Rho: ComponentType<IconProps>
  export const Tau: ComponentType<IconProps>
  export const Upsilon: ComponentType<IconProps>
  export const Phi: ComponentType<IconProps>
  export const Chi: ComponentType<IconProps>
  export const Psi: ComponentType<IconProps>
  export const Omega: ComponentType<IconProps>
}
