name: Auto Mark Photos as Completed

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  mark-photos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Execute photo marking script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        # Crear script temporal para ejecutar la función
        cat > execute_photo_marking.js << 'EOF'
        const { createClient } = require('@supabase/supabase-js');
        
        const supabaseUrl = process.env.SUPABASE_URL;
        const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
        
        if (!supabaseUrl || !supabaseKey) {
          console.error('❌ Variables de entorno de Supabase no encontradas');
          process.exit(1);
        }
        
        const supabase = createClient(supabaseUrl, supabaseKey);
        
        async function markPhotosAsCompleted() {
          try {
            console.log('🚀 Iniciando marcado automático de fotos...');
            
            // Ejecutar la función SQL que marca las fotos
            const { data, error } = await supabase.rpc('mark_photos_as_completed');
            
            if (error) {
              console.error('❌ Error ejecutando función:', error);
              process.exit(1);
            }
            
            console.log('✅ Función ejecutada correctamente');
            console.log('📊 Resultados:', JSON.stringify(data, null, 2));
            
            // Verificar resultados
            if (data && data.total_updated > 0) {
              console.log(`🎉 Se marcaron ${data.total_updated} vehículos como fotografiados`);
            } else {
              console.log('ℹ️ No se encontraron vehículos para marcar como fotografiados');
            }
            
          } catch (error) {
            console.error('❌ Error:', error);
            process.exit(1);
          }
        }
        
        markPhotosAsCompleted();
        EOF
        
        # Instalar dependencias necesarias
        npm install @supabase/supabase-js
        
        # Ejecutar el script
        node execute_photo_marking.js 