name: Mark Photos Automatically

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  mark-photos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Supabase client
      run: npm install @supabase/supabase-js
      
    - name: Execute photo marking script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        echo "🔍 Verificando variables de entorno..."
        echo "SUPABASE_URL: ${{ secrets.SUPABASE_URL != '' && '✅ Configurado' || '❌ No configurado' }}"
        echo "SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY != '' && '✅ Configurado' || '❌ No configurado' }}"
        
        # Crear script temporal para ejecutar la función
        cat > execute_photo_marking.js << 'EOF'
        const { createClient } = require('@supabase/supabase-js');
        
        const supabaseUrl = process.env.SUPABASE_URL;
        const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
        
        console.log('🔍 Verificando variables de entorno...');
        console.log('SUPABASE_URL:', supabaseUrl ? '✅ Configurado' : '❌ No configurado');
        console.log('SUPABASE_SERVICE_ROLE_KEY:', supabaseKey ? '✅ Configurado' : '❌ No configurado');
        
        if (!supabaseUrl || !supabaseKey) {
          console.error('❌ Variables de entorno de Supabase no encontradas');
          console.error('Por favor, configura SUPABASE_URL y SUPABASE_SERVICE_ROLE_KEY en GitHub Secrets');
          process.exit(1);
        }
        
        const supabase = createClient(supabaseUrl, supabaseKey);
        
        async function markPhotosAsCompleted() {
          try {
            console.log('🚀 Iniciando marcado automático de fotos...');
            
            // Verificar conexión a Supabase
            console.log('🔗 Probando conexión a Supabase...');
            const { data: testData, error: testError } = await supabase.from('fotos').select('count').limit(1);
            
            if (testError) {
              console.error('❌ Error conectando a Supabase:', testError);
              process.exit(1);
            }
            
            console.log('✅ Conexión a Supabase exitosa');
            
            // Ejecutar la función SQL que marca las fotos
            console.log('📊 Ejecutando función mark_photos_as_completed...');
            const { data, error } = await supabase.rpc('mark_photos_as_completed');
            
            if (error) {
              console.error('❌ Error ejecutando función:', error);
              console.error('Detalles del error:', JSON.stringify(error, null, 2));
              process.exit(1);
            }
            
            console.log('✅ Función ejecutada correctamente');
            console.log('📊 Resultados:', JSON.stringify(data, null, 2));
            
            // Verificar resultados
            if (data && data.total_updated > 0) {
              console.log(`🎉 Se marcaron ${data.total_updated} vehículos como fotografiados`);
            } else {
              console.log('ℹ️ No se encontraron vehículos para marcar como fotografiados');
            }
            
          } catch (error) {
            console.error('❌ Error inesperado:', error);
            console.error('Stack trace:', error.stack);
            process.exit(1);
          }
        }
        
        markPhotosAsCompleted();
        EOF
        
        # Ejecutar el script
        node execute_photo_marking.js 